### ISSUE TITLE
HEIC wrongly orientated on preview but not on actual file

### ISSUE THREAD

**Issue by AiroPi** [pulsejet/memories#1120]
**Describe the bug**
Some of my HEIC files are wrongly oriented in the timeline view and in the fullscreen view, but they got correctly oriented when I zoom in (when the image is fully loaded)

**To Reproduce**
These files, for example, have this strange behavior:
[Archive.zip](https://github.com/pulsejet/memories/files/14877901/Archive.zip)

**Platform:**
- OS: MacOS
- Browser: Chrome
- Memories Version: latest
- Nextcloud Version: 28.0.3

**Comment by pulsejet** [comment]
These look fine to me. Did you upload them to Nextcloud a long time ago? I think the HEIC orientation bug was fixed in Nextcloud 27, so you might need a preview regeneration (I plan to add this).

Can you try to re-upload the files to a different folder and see if that fixes it?

![image](https://github.com/pulsejet/memories/assets/10709794/fa91a1f2-5c95-4d7e-8762-f994619e3977)

**Comment by AiroPi** [comment]
I ran the command `php occ preview:generate <path>`, it tells "preview generated", but it is still wrongly oriented in my browser.

**Comment by pulsejet** [comment]
Hmm what version of Imagick do you have? The Memories admin panel should show this

**Comment by AiroPi** [comment]
Can't see imagick version on memories admin settings.
I use Nextcloud AIO, with the imaginary extension:
> Imaginary (for previews of heic, heif, illustrator, pdf, svg, tiff and webp.)

But here is some informations I was able to find:
```
imagick

imagick module => enabled
imagick module version => 3.7.0
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
Imagick compiled with ImageMagick version => ImageMagick 7.1.1-26 Q16-HDRI x86_64 21914 https://imagemagick.org
Imagick using ImageMagick library version => ImageMagick 7.1.1-26 Q16-HDRI x86_64 21914 https://imagemagick.org
```

**Comment by pulsejet** [comment]
> I use Nextcloud AIO, with the imaginary extension

Ah, that's the problem. Get rid of imaginary, it doesn't work right with HEIC and is mostly useless anyway (actually slower for me compared to the default preview pipeline)

**Comment by AiroPi** [comment]
I won't run into any issue with other formats by doing this ? (It is said that imaginary is used to generate preview for other files like pdf...)
I will disable it anyway if it fix the problem for my HEIC pictures, which is the most important for now.

**Comment by pulsejet** [comment]
I don't think it's used for anything other than images. Not sure though.

**Comment by pulsejet** [comment]
Closing this cause we can't fix it here and it's a confirmed upstream bug

**Comment by AiroPi** [comment]
I know this is not really memories-related, but by disabling imaginary, I can't generate preview for HEIC at all on an AIO instance.
What is the tool normally used to generate preview for HEIC files ?

<img width="804" alt="image" src="https://github.com/pulsejet/memories/assets/47398145/a2973b0c-02e8-4cdb-a8b7-7bed6ad4771d">

**Comment by AiroPi** [comment]
> Did you enable HEIC in the admin panel of memories? Imagick is used for this

I haven't any option for this. Maybe Imagick isn't available through AIO, I don't know. I guess the menu should be "File Support" as it appear in the table of content, but there is nothing in the settings.

**Comment by pulsejet** [comment]
Huh is that the only missing section? It should be something like this. Any errors in JS console?

![image](https://github.com/pulsejet/memories/assets/10709794/eec307f8-2f58-425b-8305-3673375dad6f)

**Comment by AiroPi** [comment]
@pulsejet I get this : `AdminMain.vue:107 TypeError: this.providers(...).includes is not a function`

**Comment by pulsejet** [comment]
Fix is on the way. In the meanwhile, you can either add the two lines in this patch (https://github.com/pulsejet/memories/commit/3f652d139f110a0aeb20e454f3404233a8d2a813) to `AdminController.php` OR reformat your `config.php` as follows:

Replace

```php
'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\TXT',
    1 => 'OC\\Preview\\MarkDow
     ...
);
```

with

  'enabledPreviewProviders' =>
  array (
    'OC\\Preview\\TXT',
    'OC\\Preview\\MarkDown',
    ...
)
```

i.e. remove ALL the number and arrows

**Comment by AiroPi** [comment]
I did the first option (added the line in AdminController.php), however the preview aren't generated. I have this error in the nextcloud console:
> Imaginary preview provider is enabled, but no url is configured. Please provide the url of your imaginary server to the 'preview_imaginary_url' config variable.

I guess I only needs to remove `6 => 'OC\\Preview\\Imaginary',` in my config.php right?

**Comment by AiroPi** [comment]
I get `No preview generator available for file of typeimage/heic` when I use `occ preview:generate` while HEIC is enabled in Memories settings

**Comment by pulsejet** [comment]
Hmmm that does the config file look like?

**Comment by AiroPi** [comment]
Here is the full config file:
```php
<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'check_data_directory_permissions' => false,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'nextcloud-aio-redis',
    'password' => 'ab2e7cbc3b4db507c493d4d06fa775dec9498febe7d82849',
    'port' => 6379,
  ),
  'overwritehost' => 'cloud.schauli.com',
  'overwriteprotocol' => 'https',
  'passwordsalt' => 'sL20+m8qv7ahhUaTVg8eUAqeAZwW6Y',
  'secret' => 'k4e7jiTgKpEup2KjwQFLo2ygtkEnTmvD7/duFFpfoFuziUNq',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'cloud.schauli.com',
  ),
  'datadirectory' => '/mnt/ncdata',
  'dbtype' => 'pgsql',
  'version' => '28.0.4.1',
  'overwrite.cli.url' => 'https://cloud.schauli.com/',
  'dbname' => 'nextcloud_database',
  'dbhost' => 'nextcloud-aio-database',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_nextcloud',
  'dbpassword' => 'ab2571e59b5f07537b099e950e6a938746108b3f0450d161',
  'installed' => true,
  'instanceid' => 'ocnuj7iqjyfc',
  'maintenance' => false,
  'updater.release.channel' => 'stable',
  'updatedirectory' => '/nc-updater',
  'loglevel' => '2',
  'app_install_overwrite' => 
  array (
    0 => 'nextcloud-aio',
  ),
  'log_type' => 'file',
  'logfile' => '/var/www/html/data/nextcloud.log',
  'log_rotate_size' => '10485760',
  'log.condition' => 
  array (
    'apps' => 
    array (
      0 => 'admin_audit',
    ),
  ),
  'preview_max_x' => '2048',
  'preview_max_y' => '2048',
  'jpeg_quality' => '60',
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\MarkDown',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\OpenDocument',
    4 => 'OC\\Preview\\Movie',
    5 => 'OC\\Preview\\Krita',
    6 => 'OC\\Preview\\TIFF',
    7 => 'OC\\Preview\\Image',
    8 => 'OC\\Preview\\HEIC',
  ),
  'enable_previews' => true,
  'upgrade.disable-web' => true,
  'mail_smtpmode' => 'smtp',
  'trashbin_retention_obligation' => 'auto, 30',
  'versions_retention_obligation' => 'auto, 30',
  'activity_expire_days' => '30',
  'simpleSignUpLink.shown' => false,
  'share_folder' => '/Shared',
  'one-click-instance' => true,
  'one-click-instance.user-limit' => 100,
  'one-click-instance.link' => 'https://nextcloud.com/all-in-one/',
  'htaccess.RewriteBase' => '/',
  'files_external_allow_create_new_local' => true,
  'trusted_proxies' => 
  array (
    0 => '127.0.0.1',
    1 => '::1',
    2 => '172.19.0.3',
  ),
  'allow_local_remote_servers' => true,
  'upgrade.cli-upgrade-link' => 'https://github.com/nextcloud/all-in-one/discussions/2726',
  'davstorage.request_timeout' => 3600,
  'dbpersistent' => false,
  'memories.exiftool' => '/var/www/html/custom_apps/memories/bin-ext/exiftool-amd64-musl',
  'memories.vod.path' => '/var/www/html/custom_apps/memories/bin-ext/go-vod-amd64',
  'memories.vod.ffmpeg' => '/usr/bin/ffmpeg',
  'memories.vod.ffprobe' => '/usr/bin/ffprobe',
  'data-fingerprint' => 'b0570a9035c3bba73c00072e2003b7a7',
  'mail_from_address' => 'nextcloud',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'schauli.fr',
  'mail_smtphost' => 'mail61.lwspanel.com',
  'mail_smtpport' => '465',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'nextcloud@schauli.fr',
  'mail_smtppassword' => 'nJ5!zq9k5HRR4fH',
  'mail_smtpsecure' => 'ssl',
  'default_phone_region' => 'FR',
  'appsallowlist' => false,
  'facerecognition.external_model_url' => 'nextcloud-aio-facerecognition:5000',
  'facerecognition.external_model_api_key' => 'some-super-secret-api-key',
  'enabledFaceRecognitionMimetype' => 
  array (
    0 => 'image/jpeg',
    1 => 'image/png',
    2 => 'image/heic',
    3 => 'image/tiff',
    4 => 'image/webp',
  ),
  'memories.vod.disable' => false,
  'memories.vod.connect' => 'nextcloud-aio-memories:47788',
  'maintenance_window_start' => 1,
  'preview_imaginary_key' => '0211ab23f43701d1ad6a8ab35f7607be4b4a137f422f212d',
  'memories.gis_type' => 2,
  'memories.db.triggers.fcu' => true,
  'memories.vod.qf' => 20,
  'memories.vod.vaapi' => true,
  'memories.vod.external' => true,
  'memories.video_default_quality' => '-2',
);
```

**Comment by pulsejet** [comment]
I removed the comment to get rid of any secrets, but that looks fine. What does the admin panel say about imagick?

**Comment by AiroPi** [comment]
> PHP-Imagick is available [ImageMagick 7.1.1-26 Q16-HDRI x86_64 21914 https://imagemagick.org].

**Comment by pulsejet** [comment]
Okay, taking a look. The only thing that pops up is the case if this imagick isn't supporting HEIC (strange)

**Comment by AiroPi** [comment]
I ran magick -list format and HEIC isn't present. I don't know if this is specific to the nextcloud container from AIO or not

**Comment by pulsejet** [comment]
You're right, the included Imagick doesn't have HEIC support. I've opened a PR at https://github.com/nextcloud/all-in-one/pull/4513 for adding support by default.

I believe you can set the `NEXTCLOUD_ADDITIONAL_APKS` to your container (though I haven't tried it). Probably something like this.

```yml
NEXTCLOUD_ADDITIONAL_APKS="imagemagick imagemagick-svg imagemagick-heic imagemagick-tiff"
```

and then restart (maybe).

**Comment by AiroPi** [comment]
Great news, it's working. HEIF are generated (and correctly oriented as well). 
However, Imaginary is still useful to generate other file formats such as PDF or illustrator files. Is there a way to use the Imagick HEIC preview generation in priority ?
Otherwise, I don't think it is really an issue, I prefer to do without PDF previews.

**Comment by pulsejet** [comment]
> However, Imaginary is still useful to generate other file formats such as PDF or illustrator files. Is there a way to use the Imagick HEIC preview generation in priority ?

Doesn't seem so. Imaginary always takes priority.
