### ISSUE TITLE
Error Adminpanel after 7.3 - Invalid type for system config preview_max_x, expected integer, got string

### ISSUE THREAD

**Issue by apg1980** [pulsejet/memories#1168]
**Describe the bug**
No Adminsettings visible in Adminpanel after Update to 7.3, insted popup error "Invalid type for system config preview_max_x, expected integer, got string"

**To Reproduce**
Just open Adminpanel

**Screenshots**
![image](https://github.com/pulsejet/memories/assets/9514965/76407ece-fdd8-4aa9-82e3-3a75c071f833)

**Platform:**

- OS: Ûbuntu 22.04 LTS
- Browser: Brave
- Memories Version: 7.3
- Nextcloud Version: 29
- PHP Version: 8.1

**Additional context**

- Any errors in the JS console? 
- Any errors in the Nextcloud server logs? no

**Comment by pulsejet** [comment]
Change `preview_max_x` to an integer in your `config.php`

**Comment by apg1980** [comment]
got it the value in config.php for preview_max_x was encapsulated like '1024' the quotes exists since years without issues, after removing it the adminpanel opened again.

**Comment by pulsejet** [comment]
Correct, then it has been wrong since years ;)

**Comment by tobiaseigen** [comment]
Sorry to be obtuse, but I am not sure what to do here. My config file now looks like the below but I am still getting errors. Should I also change any other settings in the same way, like the immediately following one? 

```
  'preview_max_x' => 2048,
  'preview_max_y' => '2048',
```

**Comment by steadfasterX** [comment]
@pulsejet I had this too and I think and this might happen when users (like me) wrongly used the occ utility to set these:

~~~
occ config:system:set preview_max_y --value="2048"
 System config value preview_max_y set to string 2048

occ config:system:set preview_max_x --value="2048"
 System config value preview_max_x set to string 2048
~~~

This sets in config.php:

~~~
  'preview_max_x' => '2048',
  'preview_max_y' => '2048',
~~~

I tried the occ commands without quotes, single quotes and double quotes but they are always converted as string with single quotes. the documention for the previewgenerator clearly says "modify config.php.." and not "use occ tool" so .. :P

I guess I was misled by https://github.com/nextcloud/previewgenerator?tab=readme-ov-file#i-dont-want-to-generate-all-the-preview-sizes and simply tried to set the preview_max_* values the same way.

**Comment by pulsejet** [comment]
Ah! Interestingly, this might explain why people have been having preview generation issues; at least memories should be able to catch this now.

**Comment by lepef32** [comment]
Hi everyone,
Same issue here (On Nextcloud AIO).
As per the message above the issue seems very easy to fix but the point is that i cannot find
  'preview_max_x' => 2048,
  'preview_max_y' => 2048,
  in the config.php file. (at least the Nextcloud AIO one) i accessed it that way :  
_/docker/volumes/nextcloud_aio_mastercontainer# sudo docker run -it --rm --volume nextcloud_aio_nextcloud:/var/www/html:rw alpine sh -c "apk add --no-cache nano && nano /var/www/html/config/config.php"_

Does Memories have it own config.php and in such case where is it located ? 

Thanks a lot.

(My config is : Nextcloud AIO installed on a standalone server (OS=OMV) via Docker )

**Comment by pulsejet** [comment]
You could have other config files in the same directory. But memories doesn't have it's own

**Comment by ShapeShifter499** [comment]
@pulsejet I have not read through all of the code. Does memories not add those values by default to config.php?

**Comment by pulsejet** [comment]
No

**Comment by pulsejet** [comment]
To clarify, memories doesn't add these values; the only time you'll need to fix the type is if you set it manually earlier (to an invalid string value)

**Comment by mrfr34ky** [comment]
Hi,

Was just about to file a bugreport for this. Any idea how can I fix this? Or just sit tight and wait? :) ps running truenas/truecharts for the app and the max height and width are set in the app config at installation

Thank you!

**Comment by r100gs** [comment]
Hello,  Inhave NC AIOS 28 running with memories. I never set max Pixel, but still cannot access memories settings page. How can I change this values within NC AIOS? Any ideas?

Thank you, Stefan

**Comment by marcello-dev** [comment]
Hello, I have the same issue after installing Memories app. Never touched config.php properties since I installed Nextcloud last week with AIO. Why is this issue closed? Are there instructions to fix the issue for AIO installations?

**Comment by pulsejet** [comment]
https://github.com/nextcloud/all-in-one/pull/4617

**Comment by pulsejet** [comment]
Anybody facing this issue please try upgrading to 7.3.1 first

**Comment by Sabering1** [comment]
fixed

**Comment by r100gs** [comment]
Fixed with 7.3.1!

THX

**Comment by sol8712** [comment]
> Anybody facing this issue please try upgrading to 7.3.1 first

The update absolutly fixed it for me, i took no manual action, thank you! No issues more issues with my setup.

**Comment by mrfr34ky** [comment]
Still happening for me :/. Also tried to set it manually with the occ command. No luck either.

**Comment by pulsejet** [comment]
It has to be set to a string _somewhere_.

You could try `occ maintenance:repair`, then restart PHP server

**Comment by mrfr34ky** [comment]
Okk will try how do I restart the php server after please?

**Comment by pulsejet** [comment]
Depends on how you deployed Nextcloud.

**Comment by mrfr34ky** [comment]
Fixed, I think it had to do with some browser caching... works on an other PC. Thanks a ton!

**Comment by maxgamme** [comment]
Hi Everyone the issues is not in the string 
'preview_max_x' =>  2048,
or here 'preview_max_y' =>  2048,
but here
'preview_max_memory' => 256, 
in 'preview_max_memory' not in 'preview_max_y' =>  2048,
was so simple everyone missed it i guess

**Comment by dillardblom** [comment]
Just to add a note to this thread:

I had this problem also, but couldn't fix it first, since `occ config:system:get preview_max_memory` gave a correct value of 256 and setting it with `occ config:system:set preview_max_memory --value 256` didn't resolve anything. 

When diving into the config file I found: 

<img width="413" alt="Image" src="https://github.com/user-attachments/assets/07638160-04f9-4ee6-9138-e9fc2b3c6adb" />

That was not noticed through the occ-commands, but if Memories expect an integer, this is not gonna work. Removed it manually and replaced it with ` 'preview_max_memory' => 256,` and that solved the problem. Don't know how that array came into the config, but just wanted to mention this, as this could only be found by diving into the config file...
