### ISSUE TITLE
Transcoder does not restart properly

### ISSUE THREAD

**Issue by smrganic** [pulsejet/memories#1188]
**Describe the bug**
go-vod transcoding container does not start up correctly after host reboot or container restart. I think this happens when running as non root, possibly the /tmp directory does not get destroyed / re-created correctly.

**To Reproduce**
Set up everything needed for HW transcoding to work. Verify that it works. run `docker restart <container-id>` after that the transcode container will not connect anymore.

**Screenshots**
Working config
![image](https://github.com/pulsejet/memories/assets/59741765/5aa12dc9-a784-4050-a71a-6b67b4f56060)
Output of docker logs it seems to need a toggle on / off in the admin panel to detect vaapi compatibility... This seems like another problem.
```
Fetched https://cloud.mrga.dev/index.php/apps/memories/static/go-vod?arch=x86_64 successfully!
2024/05/14 11:15:29 &{Version:0.2.5 Configured:false VersionMonitor:true Bind::47788 FFmpeg:/usr/local/bin/ffmpeg FFprobe:/usr/local/bin/ffprobe TempDir:/tmp/go-vod ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 QF:0 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale: UseTranspose:false ForceSwTranspose:false UseGopSize:false}
2024/05/14 11:15:29 Starting go-vod 0.2.5 on :47788
2024/05/14 11:15:35 &{Version:0.2.5 Configured:true VersionMonitor:true Bind::47788 FFmpeg:/usr/local/bin/ffmpeg FFprobe:/usr/local/bin/ffprobe TempDir:/tmp/go-vod ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 QF:24 VAAPI:true VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:cuda UseTranspose:true ForceSwTranspose:false UseGopSize:false}
``` 

After docker restart:
![image](https://github.com/pulsejet/memories/assets/59741765/3fdb8d5f-3e1e-47ad-8573-5122093143bf)

```
rm: cannot remove 'go-vod': Is a directory
Failed to fetch https://cloud.mrga.dev/index.php/apps/memories/static/go-vod?arch=x86_64
Are you sure the host is reachable and running Memories v6+?
Retrying in 10 seconds...
``` 

**Platform:**

- OS: Debian 12.5 LXC container running Docker 26..1.1
- Browser: N/A
- Memories Version: 7.3.1
- Nextcloud Version: 25.0.5 using nextcloud docker container https://hub.docker.com/_/nextcloud
- PHP Version: 8.2.19

**Additional context**
The problem goes away if I force recreate the whole stack.
`docker compose up -d --force-recreate`

**Comment by pulsejet** [comment]
This should be fixed now. Pull in the latest image of `radialapps/go-vod`

**Comment by AidanNelson** [comment]
@pulsejet I'm still seeing this issue in the nextcloud-AIO community container version of memories.  I've pulled the latest image using `sudo docker pull radialapps/go-vod` and restarted the full set of AIO containers.  

Any thoughts on how to debug?

Thanks!
