### ISSUE TITLE
Edit Date/Time - Error

### ISSUE THREAD

**Issue by EVOTk** [pulsejet/memories#56]
Hello,
I saw that in the new version it was possible to edit data but I can't use it?
![image](https://user-images.githubusercontent.com/45015615/192370379-54d228fa-7690-4a72-a8c6-b782c44aaa57.png)

I fill in: `2017` `03` `12` `15` `50`
But I have an error:
![image](https://user-images.githubusercontent.com/45015615/192370421-1430aebb-c1d5-4190-bb0c-8b0d9898ea4f.png)

Not the expected format?

In my Console ( Firefox ) : 
```
XHRPATCHhttps://cloud.ndd/apps/memories/api/edit/430588
[HTTP/2 400 Bad Request 81ms]

	
PATCH
	https://cloud.ndd/apps/memories/api/edit/430588
État
400
Bad Request
VersionHTTP/2
Transfert917 o (taille 52 o)
Politique de référentsame-origin
Priorité de la requêteHighest

    	
    cache-control
    	no-cache, no-store, must-revalidate
    cache-control
    	no-transform
    content-length
    	52
    content-security-policy
    	default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
    content-type
    	application/json; charset=utf-8
    date
    	Mon, 26 Sep 2022 20:12:26 GMT
    expires
    	Thu, 19 Nov 1981 08:52:00 GMT
    feature-policy
    	autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
    pragma
    	no-cache
    referrer-policy
    	no-referrer
    referrer-policy
    	same-origin
    server
    	nginx
    strict-transport-security
    	max-age=63072000
    x-content-type-options
    	nosniff
    x-download-options
    	noopen
    X-Firefox-Spdy
    	h2
    x-frame-options
    	SAMEORIGIN
    x-permitted-cross-domain-policies
    	none
    x-request-id
    	RKXK2tuD8wQXM8jK98K6
    x-robots-tag
    	none
    x-robots-tag
    	none
    x-ua-compatible
    	IE=Edge
    x-xss-protection
    	1; mode=block
    x-xss-protection
    	1; mode=block
    	
    Accept
    	application/json, text/plain, */*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
    Connection
    	keep-alive
    Content-Length
    	35
    Content-Type
    	application/json
    Cookie
    	__Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=User; nc_token=PhFZ07xVK%2BBKXqZyWYUYLjg4ZI34ux%2FE; nc_session_id=ndvh4do7g09jj9tlrk6jfmifll; oc_sessionPassphrase=%2F6K2NxCNRHUxtoCrakGIkUO%2BsW9bBF4TEEiYnmMLIx0rniYP5vltPq%2BzuKhntZhOj9GtGaH9yvY7nbf9%2B4JhMSnaegdfCUmvyNMBVKrMhl4u4kR21WK%2Fxwoh65Pne4XN; ocge4bpxpgxo=ndvh4do7g09jj9tlrk6jfmifll
    DNT
    	1
    Host
    	cloud.ndd
    Origin
    	https://cloud.ndd
    Referer
    	https://cloud.ndd/apps/memories/
    requesttoken
    	Aw/yBBzhnViS933Je7Q9P/3G37Jn4yzI17lCBNLvGv4=:KF6BbC+k9T/3sDWnFvkLSJuitfsvgUDw/I0oYoCZfqQ=
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0```

**Comment by pulsejet** [comment]
Trying to figure out what's happening here. What do the boxes say before you change the value?

**Comment by EVOTk** [comment]
Hello,
Here is the indication of the original boxes:

![image](https://user-images.githubusercontent.com/45015615/192464231-f369f1d1-7174-4a29-a01e-48d97a55d9a6.png)

**Comment by pulsejet** [comment]
Please try with v2.1.3

**Comment by EVOTk** [comment]
It works perfectly! Thanks

**Comment by EVOTk** [comment]
Hello,
Sometimes I can't date several photos at the same time. However, they do not pose any problem for being dated individually.
The photos do not pose a problem to be dated individually.

When do you think @pulsejet 
Thx

![2022-09-29 22-13-14](https://user-images.githubusercontent.com/45015615/193132867-5ebc821c-2b76-42c6-8847-919299967ae1.png)

![2022-09-29 22-13-34](https://user-images.githubusercontent.com/45015615/193132875-8df700ef-6e9b-490f-99fa-568387367106.png)

![2022-09-29 22-13-48](https://user-images.githubusercontent.com/45015615/193132878-f14e992f-3e53-44b7-b5b2-d796ca26d614.png)


```
XHRPATCHhttps://cloud.ndd.fr/apps/memories/api/edit/425757
[HTTP/2 400 Bad Request 85ms]

	
PATCH
	https://cloud.ndd.fr/apps/memories/api/edit/425757
État
400
Bad Request
VersionHTTP/2
Transfert917 o (taille 52 o)
Politique de référentsame-origin
Priorité de la requêteHighest

    	
    cache-control
    	no-cache, no-store, must-revalidate
    cache-control
    	no-transform
    content-length
    	52
    content-security-policy
    	default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
    content-type
    	application/json; charset=utf-8
    date
    	Thu, 29 Sep 2022 20:06:45 GMT
    expires
    	Thu, 19 Nov 1981 08:52:00 GMT
    feature-policy
    	autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
    pragma
    	no-cache
    referrer-policy
    	no-referrer
    referrer-policy
    	same-origin
    server
    	nginx
    strict-transport-security
    	max-age=63072000
    x-content-type-options
    	nosniff
    x-download-options
    	noopen
    X-Firefox-Spdy
    	h2
    x-frame-options
    	SAMEORIGIN
    x-permitted-cross-domain-policies
    	none
    x-request-id
    	qj2DwiHO8vrnxUrpYJiA
    x-robots-tag
    	none
    x-robots-tag
    	none
    x-ua-compatible
    	IE=Edge
    x-xss-protection
    	1; mode=block
    x-xss-protection
    	1; mode=block
    	
    Accept
    	application/json, text/plain, */*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
    Connection
    	keep-alive
    Content-Length
    	35
    Content-Type
    	application/json
    Cookie
    	__Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=Evoluzione; nc_token=ccNWz7jaDHnJ5lzJicXTZOSZHgw0a9wh; nc_session_id=j91p9a9u61h7qv99d5r9hdt39p; oc_sessionPassphrase=%2F6K2NxCNRHUxtoCrakGIkUO%2BsW9bBF4TEEiYnmMLIx0rniYP5vltPq%2BzuKhntZhOj9GtGaH9yvY7nbf9%2B4JhMSnaegdfCUmvyNMBVKrMhl4u4kR21WK%2Fxwoh65Pne4XN; ocge4bpxpgxo=j91p9a9u61h7qv99d5r9hdt39p
    DNT
    	1
    Host
    	cloud.ndd.fr
    Origin
    	https://cloud.ndd.fr
    Referer
    	https://cloud.ndd.fr/apps/memories/
    requesttoken
    	8oGyiIsFqm3Cj4icVFfXxILKtCcU79pwxFeoZ63CyEE=:ufHmysVh0yPt3ODYYB3ivrCr13ckge1BjWT8H/uJhy8=
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0
    	```

**Comment by pulsejet** [comment]
Probably gets fixed in the next version. You can try from the master branch if you'd like.

**Comment by EVOTk** [comment]
Hello, unfortunately I still have the same problem in version 3.0.0

**Comment by pulsejet** [comment]
Perhaps this is because all the photos have the same / non-existent date.

**Comment by EVOTk** [comment]
Indeed, the selection of the 5 photos that I tried had exactly the same date

**Comment by EVOTk** [comment]
Hello,
Same in 3.1.0

![image](https://user-images.githubusercontent.com/45015615/194746314-f32e922e-54fd-431d-ab2f-15f01d0593b9.png)

![image](https://user-images.githubusercontent.com/45015615/194746360-4fddd79e-4415-4959-92cb-5240a84d39bc.png)

Let me know if I can help you determine the cause of this problem.
Individual editing works well.

```
XHRPATCHhttps://cloud.ndd/apps/memories/api/edit/425767
[HTTP/2 400 Bad Request 102ms]

	
PATCH
	https://cloud.ndd/apps/memories/api/edit/425767
État
400
Bad Request
VersionHTTP/2
Transfert917 o (taille 52 o)
Politique de référentsame-origin
Priorité de la requêteHighest

    	
    cache-control
    	no-cache, no-store, must-revalidate
    cache-control
    	no-transform
    content-length
    	52
    content-security-policy
    	default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
    content-type
    	application/json; charset=utf-8
    date
    	Sun, 09 Oct 2022 08:27:24 GMT
    expires
    	Thu, 19 Nov 1981 08:52:00 GMT
    feature-policy
    	autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
    pragma
    	no-cache
    referrer-policy
    	no-referrer
    referrer-policy
    	same-origin
    server
    	nginx
    strict-transport-security
    	max-age=63072000
    x-content-type-options
    	nosniff
    x-download-options
    	noopen
    X-Firefox-Spdy
    	h2
    x-frame-options
    	SAMEORIGIN
    x-permitted-cross-domain-policies
    	none
    x-request-id
    	5TG2qnQrUQkJHbrk7UfC
    x-robots-tag
    	none
    x-robots-tag
    	none
    x-ua-compatible
    	IE=Edge
    x-xss-protection
    	1; mode=block
    x-xss-protection
    	1; mode=block
    	
    Accept
    	application/json, text/plain, */*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
    Connection
    	keep-alive
    Content-Length
    	35
    Content-Type
    	application/json
    Cookie
    	__Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=Evoluzione; nc_token=8f0ZYSmVRrgAnjYHAJwlgwEtFNfsNGWI; nc_session_id=l4959ndst1qvsbboo326f5i2m0; oc_sessionPassphrase=%2F6K2NxCNRHUxtoCrakGIkUO%2BsW9bBF4TEEiYnmMLIx0rniYP5vltPq%2BzuKhntZhOj9GtGaH9yvY7nbf9%2B4JhMSnaegdfCUmvyNMBVKrMhl4u4kR21WK%2Fxwoh65Pne4XN; ocge4bpxpgxo=l4959ndst1qvsbboo326f5i2m0
    DNT
    	1
    Host
    	cloud.ndd
    Origin
    	https://cloud.ndd
    Referer
    	https://cloud.ndd/apps/memories/
    requesttoken
    	lXGRy7zTBSjn60L3qBLqn/nKzgO45q+WOGMy8J7VFpE=:xR76hda/fBnUvyCwwGPd/daHr1f6rID9XClDm8y/ZsE=
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0```

**Comment by pulsejet** [comment]
Yep, 3.1 doesn't have the newest fix. Probably the next patch.

**Comment by EVOTk** [comment]
Hello, the problem is apparently solved, I was able to change the date of several photos at the same time.

**Comment by pulsejet** [comment]
Nice
